version: '3'

services:
  sleek-airflow:
    image: workspace:v001  

    environment:
      - AIRFLOW__CORE__FERNET_KEY=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False         
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 

    volumes:
      - ./airflow:/opt/airflow  
      - ./bronze:/bronze
      - ./silver:/silver
      - ./gold:/gold
    ports:
      - "8080:8080"  

    command: /bin/bash -c "mkdir -p /bronze /silver /gold && airflow standalone"
